### PR TITLE
body from file

### LINKED ISSUE #16: body from file
with curl or other tools, I can easily feed the body from a file. It will be convenience for testing. 

Could we have the same feature with `aws-api-gateway-cli-tes`t? Such as:

```
  --body="@/path/to/filename"
```

I did a try, but seems this feature is not ready currently.

```
Authenticating with User Pool
Getting temporary credentials
Making API request
undefined:1
@mocks/create.json
^

SyntaxError: Unexpected token @ in JSON at position 0
```

Reference: https://stackoverflow.com/questions/15912924/how-to-send-file-contents-as-body-entity-using-curl

### PR DESCRIPTION
**Pull request by ozbillwang**
fix #16 

with option start with `@`

```
$ cat mocks/create.json
{
 "mock": "data"
}

$ node index.js --options --body='@mocks/create.json'
```

### CODE REVIEW

**Comment by jayair** [comment]
Thank for this. I'll test it out and merge it soon.

**Comment by patrykkrawczyk** [comment]
@jayair how soon? 🙃 would love this!

**Comment by jayair** [comment]
@patrykkrawczyk Thanks for the bump. I'll have a look at it in the next few days.

**Comment by jayair** [comment]
Pushed!

**Pull request merged**
